---
title: "1 - Introduction"
subtitle: "Machine learning with tidymodels"
format:
  revealjs: 
    slide-number: true
    footer: <https://workshops.tidymodels.org>
    include-before-body: header.html
    theme: [default, tidymodels.scss]
---

```{r}
#| include: false
#| file: setup.R
```

::: r-fit-text
Welcome!
:::

::: columns
::: {.column width="50%"}
### <i class="fa fa-wifi"></i>

Wi-Fi network name

`rstudio22`
:::

::: {.column width="50%"}
### <i class="fa fa-key"></i>

Wi-Fi password

`tidyverse22`
:::
:::

## Workshop policies {.smaller}

-   Identify the exits closest to you in case of emergency

-   Please review the rstudio::conf code of conduct, which applies to all workshops

-   CoC issues can be addressed three ways:

    -   **In person:** contact any rstudio::conf staff member or the conference registration desk
    -   **By email:** send a message to `conf@rstudio.com`
    -   **By phone:** call 844-448-1212

-   Please do not photograph people wearing red lanyards

-   A chill-out room is available for neurologically diverse attendees on TKTK

## Who are you?

-   You can use the magrittr `%>%` or base R `|>` pipe

-   You are familiar with functions from dplyr, tidyr, ggplot2

-   You have exposure to basic statistical concepts

-   You do **not** neeed intermediate or expert familiarity with modeling or ML

## Who are we?

::: columns
::: {.column width="50%"}
-   Hannah Frick
-   Emil Hvitfeldt
-   Max Kuhn
:::

::: {.column width="50%"}
-   Julia Silge
-   David Robinson
-   Davis Vaughan
:::
:::

## Who are we?

::: columns
::: {.column width="50%"}
-   Kelly Bodwin
-   Michael Chow
-   Pritam Dalal
-   Matt Dancho
-   Jon Harmon
:::

::: {.column width="50%"}
-   Mike Mahoney
-   Edgar Ruiz
-   Asmae Toumi
-   Qiushi Yan
:::
:::

## Asking for help

🆘 "I'm stuck"

⚠️ "I'm not stuck, but I need help on my computer"

🙋 "I need help understanding something"

##  {background-image="images/tm-org.png" background-size="900px"}

## The whole game



## Plan for this workshop

-   *Today:* your data budget, what makes a model, evaluating your model

-   *Tomorrow:* tuning hyperparameters, feature engineering, case studies

-   Log in to RStudio Cloud 💻 (or use your own computer)

-   Introduce yourself to your neighbors 👋


## {.center}

### <i class="fa fa-cloud"></i>

### Go here and log in (free):

[bit.ly/tidymodels-workshop](http://bit.ly/tidymodels-workshop)
