---
title: "8 - tidymodels and LLMs"
subtitle: "Practical Machine Learning with tidymodels"
format:
  revealjs: 
    slide-number: true
    footer: <https://workshops.tidymodels.org>
    include-before-body: header.html
    include-after-body: footer-annotations.html
    theme: [default, tidymodels.scss]
    width: 1280
    height: 720
knitr:
  opts_chunk: 
    echo: true
    collapse: true
    comment: "#>"
    fig.path: "figures/"
---

```{r setup}
#| include: false
#| file: setup.R
```

## LLMs

In many cases, the accuracy of LLMs to write code is proportional to how much of that code is online and/or scrapable. 

<br>

Generally speaking, we can enhance the AI's ability to write good code by providing resources. 

<br>

Without help, LLMs are meh at writing tidymodels code and only slightly better at Scikit-learn. 

<br> 

Let's discuss some resources to improve your experience. 


## Skills

[`https://skills.tidymodels.org/`](https://skills.tidymodels.org/) contains LLM skill files for:

 - Writing tidymodels code that will be used for data analysis
 - Developer activities such as creating a new parsnip extension, recipes steps, etc. 
 
<br>
 
The [_Getting Started_](https://skills.tidymodels.org/getting-started.html) has instructions for loading these skills. You can also just point your favorite LLM to the basic URL and ask it to install the skills. 

## Model Context Protocol (MCP) Server

There is also a [tidymodels MCP server](https://github.com/javorraca/tidymodels-mcp) that you can download and use. 

<br>

This provides AI real-time access to package documentation, function signatures, and code templates.

## Posit Assistant

With RStudio, Positron, or a terminal, you can invoke [Posit Assistant](https://assistant.posit.co/). 

<br>

You can use any framework for modeling activities (e.g., caret, mlr3, etc.). Posit Assistant tends to default to tidymodels. 

<br>

PA also has a fair amount of _wisdom_ related to ML modeling, such as not constantly evaluating the test set. 
