---
title: "Annotations"
---

```{r, echo=FALSE}
slide1 <- "01-introduction.html"

slide_link <- function(slide, title) {
  paste0("[Back to slides](", slide, "#/", title, ")")
}
```

# 01 - Introduction

## Title Slide

`r slide_link(slide1, "title-slide")`

## Workshop policies

`r slide_link(slide1, "workshop-policies")`

## Who are you?

`r slide_link(slide1, "who-are-you")`

## Who are we?

`r slide_link(slide1, "who-are-we")`

## Who are we?

`r slide_link(slide1, "who-are-we-1")`

## Asking for help

`r slide_link(slide1, "asking-for-help")`

## Plan for this workshop

`r slide_link(slide1, "plan-for-this-workshop")`

## Introduce yourself to your neighbors

`r slide_link(slide1, "section-2")`

## What is machine learning

`r slide_link(slide1, "what-is-machine-learning")`

## What is machine learning

`r slide_link(slide1, "what-is-machine-learning-1")`

## What is machine learning

`r slide_link(slide1, "what-is-machine-learning-2")`

## Your Turn

`r slide_link(slide1, "your-turn")`

## What is tidymodels?

`r slide_link(slide1, "what-is-tidymodels")`

## tidymodels.org

`r slide_link(slide1, "section-3")`

## The whole game

`r slide_link(slide1, "the-whole-game")`

## Let’s install some packages

`r slide_link(slide1, "lets-install-some-packages")`
