---
title: "5 - Feature engineering with recipes"
subtitle: "Getting More Out of Feature Engineering and Tuning for Machine Learning"
format:
  revealjs: 
    slide-number: true
    footer: <https://workshops.tidymodels.org>
    include-before-body: header.html
    include-after-body: footer-annotations.html
    theme: [default, tidymodels.scss]
    width: 1280
    height: 720
knitr:
  opts_chunk: 
    echo: true
    collapse: true
    comment: "#>"
---

```{r setup}
#| include: false
#| file: setup.R
```

Data sets we will be using:
- A less processed variant of https://modeldata.tidymodels.org/reference/leaf_id_flavia.html
    - Why? It has natural multi-choice dummy variables
    - very correlated
    - easy for people to understand
- modeldata::hotel_rates
    - has some good likelihood encoding
    - has some good non-linear effects (arrival_date_num, lead_time, stays_in_week_nights, stays_in_weekend_nights) 
    - easy for people to understand

## Leaf data set

Show the data set itself, why it is interesting

Some slides with pictures of leaves so we can understand what the features mean

## Your turn: explore leaf data

## Leaf edges

Pull out the edge predictor and explore it.

## Multi-choice dummies

Could we not just do normal dummies?
Explore and contrast with other methods
When does this break down?
- high number of levels
- ordering might matter

Show both variants we have implemented.

Talk about othering, as it can be an issue

## Other examples of Multi-choice dummies

a handful of other examples from other data sets
little explanation of data sets,
But enough that people get an idea of what to look out for

## Embeddings

Why would anyone wanna do embeddings?

- redundant information (I like Alison Horst whale graphic)
- ineffective representation
- computational speed

Methods (up for debate which to keep)

- pca
- pls
- isomap
- sparse pca

Properly need a slide as to why t-SNE doesn't work, and why we are hesitant about UMAP

Each method will show what it does (board terms),
visualize how they affect our data set and how to use them with recipes

## Hotel rates data set

Show the data set itself, why it is interesting

## Your turn: hotel rates data

## Splines

A way to handle nonlinear effects,
I think arrival_date_num, lead_time, stays_in_week_nights, stays_in_weekend_nights would be good candidates

Explanation of what a spline is and how it works

Visualization of one in use

Showing how there are different kinds of splines

periodic splines

benefits
- fast
- easy to use
- semi-interpretable

## Likelihood encoding

Bring up country, agent, company, and ask learners what we could do with these?

- dummy variables etc etc
    - why will this be a bad idea?

explain it terms of group_by summarize

talk about how we handle low count groups

at the end show that this can almost-equivalently do this through glm/stan

mention how most categorical handling can be imagined as a left-join

## Date time variables

Basically what we have from previous workshops

add "time before, time after", work well with holidays
https://feaz-book.com/datetime-advanced

mention that periodic splines also would work here
