---
title: "Notes for 1 - Introduction"
---

```{r, echo=FALSE}
slide_url <- "01-introduction.html"

slide_link <- function(title) {
  paste0("[Back to slides](", slide_url, "#/", title, ")")
}
```

## Title Slide

`r slide_link("title-slide")`

## Workshop policies

`r slide_link("workshop-policies")`

## Who are you?

`r slide_link("who-are-you")`

## Who are we?

`r slide_link("who-are-we")`

## Who are we?

`r slide_link("who-are-we-1")`

## Asking for help

`r slide_link("asking-for-help")`

## Plan for this workshop

`r slide_link("plan-for-this-workshop")`

## Introduce yourself to your neighbors

`r slide_link("section-2")`

## What is machine learning

`r slide_link("what-is-machine-learning")`

## What is machine learning

`r slide_link("what-is-machine-learning-1")`

## What is machine learning

`r slide_link("what-is-machine-learning-2")`

## Your Turn

`r slide_link("your-turn")`

## What is tidymodels?

`r slide_link("what-is-tidymodels")`

## tidymodels.org

`r slide_link("section-3")`

## The whole game

`r slide_link("the-whole-game")`

## Let’s install some packages

`r slide_link("lets-install-some-packages")`
