---
title: "1 - Introduction"
format:
  revealjs: 
    slide-number: true
    footer: <https://workshops.tidymodels.org>    
---

## tidymodels

The tidymodels framework is a collection of packages for modeling and machine learning using tidyverse principles. Our goals:

-   Enable users to fall into the "pit of success".
-   Provide a pleasant and rational interface to many types of models.
-   Provide guardrails, sometimes invisibly, that can prevent methodology errors.

##  {background="#43464B"}

[`tidymodels.org`](https://www.tidymodels.org/)

*Tidy Modeling with R* ([`tmwr.org`](https://www.tmwr.org/))

## Why R for modeling?

## Downsides to modeling in R

## Syntax for computing predicted lass probabilities

## tidymodels packages

## Example data set

## Review of Tidyverse syntax

## Example code

## Quick data investigation

## The modeling *process*

## What the modeling process usually looks like

## What are we doing with the data?

## Define the data analysis process

## Some naming conventions

## Resources
