---
title: "RStudio::conf 2022"
---

This workshop provides an introduction to machine learning with R using the [tidymodels](http://tidymodels.org "tidymodels website") framework, a collection of packages for modeling and machine learning using tidyverse principles. We will build, evaluate, compare, and tune predictive models. Along the way, we'll learn about key concepts in machine learning including overfitting, resampling, and feature engineering. Learners will gain knowledge about good predictive modeling practices, as well as hands-on experience using tidymodels packages like parsnip, rsample, recipes, yardstick, tune, and workflows.

## Where/When 

Washington DC, July 25-26th (9:00 A.M. -- 5:00 P.M)

## Should I take this course?

This course assumes intermediate R knowledge. If you can use the magrittr pipe and [tidyverse](http://tidyverse.org) functions from packages like readr, dplyr, tidyr, and ggplot2 to read data into R, transform and reshape data, and make a wide variety of graphs, this tutorial is for you. We expect participants to have some exposure to basic statistical concepts, but NOT intermediate or expert familiarity with modeling or machine learning.

## Instructors

Max Kuhn, Davis Vaughan, Julia Silge, Hannah Frick, Emil Hvitfeldt, Simon Couch, and David Robinson

## Content

-   [Part 1 - **Introduction**](01-introduction.html):  A review of R and tidyverse fundamentals and a high-level view of the modeling process.

-   [Part 2 - **Data Splitting and Basic Modeling**](02-data-usage-and-modeling.html):  The how and why of partitioning your data. An overview of Base R modeling syntax. An introduction to the parsnip package for creating models. 

-   [Part 3 - **Evaluating Models**](03-model-evaluation.html):  Once you have a model, how to you properly tell if it is any good? Introduces resampling tools for model evaluation.  

