---
title: "1 - Introduction - Classwork"
subtitle: "Practical Machine Learning with tidymodels"
editor_options:
  chunk_output_type: console
---

We recommend restarting R between each slide deck!

## Getting the materials

If you are working locally:

```{r}
#| eval: false

# local download
usethis::use_course(
  "https://github.com/tidymodels/workshops/archive/refs/heads/release.zip",
  destdir = "some_path"
)
```

## Your turn

How are statistics and machine learning related?

How are they similar? Different?

## What is tidymodels?

```{r}
library(tidymodels)
```

## Let's install some packages

If you are using your own laptop instead of Posit Cloud:

```{r}
#| eval: false

# Install the packages for the workshop
# (this list is maintained in index.qmd)
# fmt: skip
pkgs_core <- c("dimRed", "embed", "extrasteps", "future", "igraph", "mirai",
  "parallelly", "probably", "RANN", "ranger", "RcppML", "rpart.plot",
  "splines2", "tidymodels", "xgboost")

# fmt: skip
pkgs_extras <- c("bonsai", "brulee", "Cubist", "desirability2", "earth",
  "finetune", "important", "kknn", "lightgbm", "lme4", "rules", "stacks")

install.packages(c(pkgs_core, pkgs_extras))
```

`almanac` (used in deck 07) was archived from CRAN on 2026-08-22, so it comes from GitHub:

```{r}
#| eval: false

install.packages("pak")
pak::pak("davisvaughan/almanac")
```
