---
title: "Extras - Recipes - Classwork"
subtitle: "Machine learning with tidymodels"
editor_options: 
  chunk_output_type: console
---

We recommend restarting R between each slide deck!

## Setup

Setup from deck 3

```{r}
library(tidymodels)
library(modeldatatoo)

taxi <- data_taxi()

set.seed(123)
taxi_split <- initial_split(taxi, prop = 0.8, strata = tip)
taxi_train <- training(taxi_split)
taxi_test <- testing(taxi_split)
```

## Your turn

Take the recipe and `prep()` then `bake()` it to see what the resulting data set looks like.

`step_other()` has an argument `threshold` that defaults to `0.05`. Change it to see what happens to the number of columns.

Try removing steps to see how the results changes.

```{r}
rec_spec <- recipe(tip ~ ., data = taxi_train) %>%  
  step_unknown(all_nominal_predictors()) %>%  
  step_other(all_nominal_predictors()) %>%  
  step_dummy(all_nominal_predictors()) %>%  
  step_zv(all_predictors()) %>%  
  step_log(distance) %>% 
  step_normalize(all_numeric_predictors())
```


