---
title: "1 - Introduction"
format:
  revealjs: 
    slide-number: true
    footer: <https://workshops.tidymodels.org>
    theme: [default, tidymodels.scss]
---

```{r}
#| include: false
#| file: setup.R
```

## part 1 - introduction

 * using R for modeling (good and bad parts)
 * introduce tidymodels
 * tidyverse review
 * hands-on: example data warm up
 * the model versus the modeling process
 * naming conventions

* the whole game, this is the process and we are at this part (graphic?); use a workflow (and explain briefly) 

* move feature engineering to second day

* modeling -> resampling -> tune then get to feature engineering and workflows

* data splitting
* modeling
  - walk through multiple models
  - workflows
* resample the model 
* tuning 
* feat eng + workflows

Data: 

 * AD data for first day 
 * hockey for feature engineering etc
 * flights for case study

- Day 1
  - intro
  - whole game
  - Dataset 1
  - data splitting
  - modeling + workflow
  - yardstick
  - resample + fit_resamples()
  - glimpse of tune_grid
  
- Day 2
  - Remind them how fit_resamples() worked
  - tune_grid() on Dataset 1
  - Switch to Dataset 2
  - Feature engineering on Dataset 2
  - Modeling + Tuning on Dataset 2
